/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unigran.views.cadastro;

import br.com.unigran.DTO.FuncaoDTO;
import br.com.unigran.DTO.GenericoDTO;
import br.com.unigran.DTO.LoginDTO;
import br.com.unigran.DTO.RecepcionistaDTO;
import br.com.unigran.controller.FuncaoController;
import br.com.unigran.controller.LoginController;
import br.com.unigran.controller.RecepcionistaController;
import br.com.unigran.util.PainelInterface;

/**
 *
 * @author user
 */
public class CadastroFuncionarioPanel extends PainelInterface {

    /**
     * Creates new form CadastroFuncionarioPanel
     */
    public CadastroFuncionarioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jLabel2.setText("Username");
        add(jLabel2);
        add(campoUsername);

        jLabel3.setText("Senha");
        add(jLabel3);
        add(campoSenha);

        jLabel1.setText("Nome");
        add(jLabel1);
        add(campoNome);
    }// </editor-fold>//GEN-END:initComponents

    private RecepcionistaDTO recepcionistaDTO;
    private RecepcionistaController recepcionistaController;
    private FuncaoController funcaoController;
    private LoginController loginController;
    
    @Override
    public GenericoDTO salvar() {
        loginController = new LoginController();
        funcaoController = new FuncaoController();
        recepcionistaController = new RecepcionistaController();
        
        if(recepcionistaDTO != null)
            recepcionistaDTO = new RecepcionistaDTO();
        
        String username = campoUsername.getText();
        String password = campoSenha.getText();
                   
        LoginDTO loginCadastrado = new LoginDTO();
        loginCadastrado.loginUsername = username;
        loginCadastrado.senha = password;
        
        FuncaoDTO funcaoDTO = funcaoController.buscarPorNome("Recepcionista");
        
        loginCadastrado.funcao = funcaoDTO;
        
        recepcionistaDTO.nome = campoNome.getText();
        recepcionistaDTO.login = loginCadastrado;
        
        try{
            loginController.salvar(loginCadastrado);
            recepcionistaController.salvar(recepcionistaDTO);
        }catch(Exception ex){
            ex.getMessage();
        }
        
        return recepcionistaDTO;
    }

    @Override
    public void preencheCampos(GenericoDTO dto) {
        this.recepcionistaDTO =(RecepcionistaDTO) dto;
        campoNome.setText(this.recepcionistaDTO.nome);
        campoUsername.setText(this.recepcionistaDTO.login.loginUsername);
        campoSenha.setText(this.recepcionistaDTO.login.senha);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
