/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unigran.views.cadastro;

import br.com.unigran.DTO.DentistaDTO;
import br.com.unigran.DTO.FuncaoDTO;
import br.com.unigran.DTO.GenericoDTO;
import br.com.unigran.DTO.LoginDTO;
import br.com.unigran.controller.DentistaController;
import br.com.unigran.controller.FuncaoController;
import br.com.unigran.controller.LoginController;
import br.com.unigran.util.PainelInterface;

/**
 *
 * @author user
 */
public class CadastroDentistaPanel extends PainelInterface {

    /**
     * Creates new form CadastroDentista
     */
    public CadastroDentistaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoIdUsuario = new javax.swing.JTextField();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);

        jLabel2.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel2, gridBagConstraints);

        campoUsuario.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        add(campoUsuario, gridBagConstraints);

        jLabel1.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(jLabel1, gridBagConstraints);

        campoIdUsuario.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        add(campoIdUsuario, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private DentistaDTO dentistaDTO;
    private FuncaoController funcaoController;
    private LoginController loginController;
    private DentistaController dentistaController;
    
    @Override
    public GenericoDTO salvar() {
        dentistaController = new DentistaController();
        loginController = new LoginController();
        funcaoController = new FuncaoController();
        
         if( dentistaDTO == null )
            dentistaDTO= new DentistaDTO();
         
        String username = campoUsuario.getText();
        String id = campoIdUsuario.getText();
                  
        LoginDTO loginBuscado = loginController.buscaIdLogin(id);
                        
        dentistaDTO.nomeDentista = campoUsuario.getText();
        dentistaDTO.login = loginBuscado;
        
        try{
           dentistaController.salvar(dentistaDTO);
            System.out.println(dentistaDTO);
        }catch(Exception ex){
            ex.getMessage();
        }
        
        return dentistaDTO;
    }

    @Override
    public void preencheCampos(GenericoDTO dto) {
        this.dentistaDTO =(DentistaDTO) dto;
        campoUsuario.setText(this.dentistaDTO.nomeDentista);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoIdUsuario;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
