/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.unigran.views.cadastro;

import br.com.unigran.DTO.AgendamentoDTO;
import br.com.unigran.DTO.ConsultaDTO;
import br.com.unigran.DTO.DentistaDTO;
import br.com.unigran.DTO.GenericoDTO;
import br.com.unigran.DTO.PacienteDTO;
import br.com.unigran.controller.AgendamentoController;
import br.com.unigran.controller.ConsultaController;
import br.com.unigran.controller.DentistaController;
import br.com.unigran.controller.PacienteController;
import br.com.unigran.util.PainelInterface;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class CadastroConsultaPanel extends PainelInterface {

    /**
     * Creates new form CadastroConsultaPanel
     */
    public CadastroConsultaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoObservacoes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoAnexos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNomePaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoAgendamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNomeDentista1 = new javax.swing.JTextField();

        jLabel1.setText("Observacoes");

        jLabel2.setText("Anexos");

        jLabel3.setText("Valor");

        jLabel4.setText("Paciente");

        jLabel5.setText("Dentista");

        jLabel6.setText("Agendamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(campoNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoNomeDentista1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeDentista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private ConsultaDTO consultaDTO;
    private ConsultaController consultaController;
    private PacienteController pacienteController;
    private DentistaController dentistaController;
    private AgendamentoController agendamentoController;
    
    @Override
    public GenericoDTO salvar() {
        consultaController = new ConsultaController();
        pacienteController = new PacienteController();
        dentistaController = new DentistaController();
        agendamentoController = new AgendamentoController();
        
         if( consultaDTO == null )
            consultaDTO= new ConsultaDTO();
        
        consultaDTO.observacoes = campoObservacoes.getText();
        consultaDTO.valor = Double.valueOf(campoValor.getText());
        consultaDTO.anexos = null;
        DentistaDTO dentistaEncontrado = dentistaController.buscaPorNome(campoNomeDentista1.getText());
        consultaDTO.dentista = dentistaEncontrado;
        AgendamentoDTO agendamentoEncontrado = agendamentoController.buscaPorNome(Long.valueOf(campoAgendamento.getText()));
        consultaDTO.agendamento = agendamentoEncontrado;
        PacienteDTO pacienteEncontrado = pacienteController.buscaPorNome(campoNomePaciente.getText());
        consultaDTO.paciente = pacienteEncontrado;
        
        try {
            consultaController.salvar(consultaDTO);
        } catch (Exception ex) {
            Logger.getLogger(CadastroConsultaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return consultaDTO;
    }

    @Override
    public void preencheCampos(GenericoDTO dto) {
        this.consultaDTO =(ConsultaDTO) dto;
        campoObservacoes.setText(this.consultaDTO.observacoes);
        campoValor.setText(this.consultaDTO.valor.toString());
        campoNomeDentista1.setText(this.consultaDTO.dentista.nomeDentista);
        campoNomePaciente.setText(this.consultaDTO.paciente.nome);
        campoAgendamento.setText(this.consultaDTO.agendamento.id.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAgendamento;
    private javax.swing.JTextField campoAnexos;
    private javax.swing.JTextField campoNomeDentista1;
    private javax.swing.JTextField campoNomePaciente;
    private javax.swing.JTextField campoObservacoes;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
